name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: photo-gallery-react/package-lock.json
    
    - name: Install dependencies
      run: |
        cd photo-gallery-react
        npm ci
    
    - name: Run linting
      run: |
        cd photo-gallery-react
        npm run lint
    
    - name: Check for security vulnerabilities
      run: |
        cd photo-gallery-react
        npm audit --production
    
    - name: Build
      run: |
        cd photo-gallery-react
        npm run build
      env:
        CI: false # This prevents treating warnings as errors
        REACT_APP_VERSION: ${{ github.sha }}
    
    - name: Cache build
      uses: actions/cache@v3
      with:
        path: photo-gallery-react/build
        key: ${{ runner.os }}-build-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-build-

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./photo-gallery-react
        vercel-args: '--prod'
    
    - name: Verify deployment
      run: |
        echo "Deployment completed. Please verify at https://birhanuasmerom.vercel.app"
        echo "Commit SHA: ${{ github.sha }}" 